Repository kiwiproject/service-discovery-client, pull requests merged in 2020-11, with the labels that each got.

#42 Enable system properties to configure the embedded consul
  src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
  src/test/java/org/kiwiproject/registry/consul/server/ConsulRegistryServiceIntegrationTest.java
  src/test/java/org/kiwiproject/registry/consul/util/ConsulStarterHelper.java
Labels: enhancement

#43 Upgrade kiwiproject dependencies
  pom.xml
Labels: dependencies

#45 Switch from TravisCI to GitHub Actions for the build
  .github/workflows/build.yml
  .travis.yml.deleteme
  LICENSE.txt
  README.md
  pom.xml
Labels: refactoring

#46 Upgrade kiwiproject dependencies
  pom.xml
Labels: dependencies
